### ISSUE TITLE
The Application must be implemented PluginRegistrantCallback

### ISSUE THREAD

**Issue by GuihaiHU** [fluttercommunity/flutter_downloader#141]
version: 
flutter1.9.1+hotfix.4
flutter_downloader: "^1.3.0"

I have added `flutter_downloader` to my project as [document](https://pub.flutter-io.cn/packages/flutter_downloader) except `MyApplication.java`. I modified my `MainActivity.kt` like this
```kotlin
class MainActivity: FlutterActivity(), PluginRegistrantCallback {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }

  override fun registerWith(registry: PluginRegistry?) {
    GeneratedPluginRegistrant.registerWith(registry);
  }
}
```
However, it complains that
```
E/AndroidRuntime(28655): java.lang.AssertionError: The Application must be implemented PluginRegistrantCallback
E/AndroidRuntime(28655):        at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:106)
E/AndroidRuntime(28655):        at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java:59)
E/AndroidRuntime(28655):        at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:97)
E/AndroidRuntime(28655):        at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(28655):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(28655):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(28655):        at android.app.ActivityThread.main(ActivityThread.java:6898)
E/AndroidRuntime(28655):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28655):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/AndroidRuntime(28655):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
D/OSTracker(28655): OS Event: crash
```
What's wrong with my code? Thanks for any help~

**Comment by hnvn** [comment]
That's why it is required configuration

**Comment by GuihaiHU** [comment]
> That's why it is required configuration

hi hnvn,I do everything as document but `MyApplication.java`.

**Comment by hnvn** [comment]
I can't understand your matter, please read and follow the document carefully. You don't follow the configuration of `Application` class, that's why your project doesn't work. Here's the related document:
https://github.com/fluttercommunity/flutter_downloader/blob/master/README.md#required-configuration-1

**Comment by GuihaiHU** [comment]
I have modified `AndroidManifest.xml` in my project.However,  there is not `MyApplication.java` but `MainActivity.kt`.So I try to update `MainActivity.kt` like this 
```kotlin
class MainActivity: FlutterActivity(), PluginRegistrantCallback {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }

  override fun registerWith(registry: PluginRegistry?) {
    GeneratedPluginRegistrant.registerWith(registry);
  }
}
```
However, I complains that `E/AndroidRuntime(28655): java.lang.AssertionError: The Application must be implemented PluginRegistrantCallback`

**Comment by hnvn** [comment]
Here's the android example project:
https://github.com/fluttercommunity/flutter_downloader/tree/master/example/android
But it uses Java, you may as well convert it to kotlin in your case.

**Comment by GuihaiHU** [comment]
Thanks for your kindly response.I have found my problem.

**Comment by hnvn** [comment]
Great

**Comment by jjjachyty** [comment]
@GuihaiHU can you show MainActivity.kt code？plz

**Comment by jjjachyty** [comment]
```
import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import vn.hunghd.flutterdownloader.FlutterDownloaderPlugin;
```


just fine。

**Comment by mramirez11** [comment]
I have implemented the required configuration, however my java file extends from FlutterActivity instead of FlutterApplication, so it crashes when starting the app.
The code looked like this


```
import android.os.Bundle;
import io.flutter.app.FlutterActivity;
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.flutter.plugin.common.PluginRegistry;
import android.view.ViewTreeObserver;
import android.view.WindowManager;

public class MainActivity extends FlutterActivity implements PluginRegistry.PluginRegistrantCallback {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    boolean flutter_native_splash = true;

    ViewTreeObserver vto = getFlutterView().getViewTreeObserver();
    vto.addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
      @Override
      public void onGlobalLayout() {
        getFlutterView().getViewTreeObserver().removeOnGlobalLayoutListener(this);
        getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
      }
    });
  }

    public void registerWith(PluginRegistry registry) {
        GeneratedPluginRegistrant.registerWith(registry);
    }

}
```

The console shows the following results
`[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel vn.hunghd/downloader)`

Can you help me?
Thanks

**Comment by mohammadne** [comment]
> Thanks for your kindly response.I have found my problem.

what was the issue ?
