### ISSUE TITLE
Android registerCallback exception

### ISSUE THREAD

**Issue by idrats** [fluttercommunity/flutter_downloader#153]
This error occures when I'm trying to register callback:
```dart
FlutterDownloader.registerCallback(downloadCallback);
```

The callback is absolutely identical to example:

```dart
static void downloadCallback(
      String id, DownloadTaskStatus status, int progress) {
    print(
        'Background Isolate Callback: task ($id) is in status ($status) and process ($progress)');
    final SendPort send =
        IsolateNameServer.lookupPortByName('downloader_send_port');
    send.send([id, status, progress]);
  }
```

BTW: On iOS works fine

```
E/MethodChannel#vn.hunghd/downloader(19555): Failed to handle method call
E/MethodChannel#vn.hunghd/downloader(19555): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
E/MethodChannel#vn.hunghd/downloader(19555):    at vn.hunghd.flutterdownloader.FlutterDownloaderPlugin.registerCallback(FlutterDownloaderPlugin.java:132)
E/MethodChannel#vn.hunghd/downloader(19555):    at vn.hunghd.flutterdownloader.FlutterDownloaderPlugin.onMethodCall(FlutterDownloaderPlugin.java:63)
E/MethodChannel#vn.hunghd/downloader(19555):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#vn.hunghd/downloader(19555):    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#vn.hunghd/downloader(19555):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#vn.hunghd/downloader(19555):    at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#vn.hunghd/downloader(19555):    at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#vn.hunghd/downloader(19555):    at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#vn.hunghd/downloader(19555):    at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#vn.hunghd/downloader(19555):    at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#vn.hunghd/downloader(19555):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#vn.hunghd/downloader(19555):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter (19555): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, java.lang.Integer cannot be cast to java.lang.Long, null)
E/flutter (19555): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (19555): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (19555): <asynchronous suspension>
E/flutter (19555): #2      FlutterDownloader.registerCallback (package:flutter_downloader/src/downloader.dart:385:14)
E/flutter (19555): #3      _AttachTabState.didChangeDependencies.<anonymous closure> (package:my_app/widgets/detachment_tabs/attach_tab.dart:51:25)
E/flutter (19555): #4      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (19555): #5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (19555): #6      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
E/flutter (19555): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
E/flutter (19555): #8      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
E/flutter (19555): #9      Future._completeWithValue (dart:async/future_impl.dart:522:5)
E/flutter (19555): #10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
E/flutter (19555): #11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
E/flutter (19555): #12     DocumentsClient.findByDetachmentId (package:openagent_api_client/src/documents_client.dart)
E/flutter (19555): <asynchronous suspension>
E/flutter (19555): #13     _AttachTabState.didChangeDependencies (package:my_app/widgets/detachment_tabs/attach_tab.dart:45:10)
...
```

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6
    18G103, locale ru-RU)
    • Flutter version 1.9.1+hotfix.6 at /Users/idrats/Documents/flutter
    • Framework revision 68587a0916 (7 weeks ago), 2019-09-13 19:46:58
      -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK 
    version 28.0.3)
    • Android SDK at /Users/idrats/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native
      profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android
      10 (API 29) (emulator)
```

**Comment by iperfectapp** [comment]
flutter_downloader configuration is becoming more and more complex

**Comment by Alamusitl** [comment]
I have this problem too.

**Comment by JHBitencourt** [comment]
Same problem here. `flutter_downloader: ^1.3.3`

Any news?

**Comment by SergeShkurko** [comment]
@hnvn can you help?

**Comment by SergeShkurko** [comment]
The problem was in converting `Long` to `long`
