### ISSUE TITLE
Ouestion about some code .

### ISSUE THREAD

**Issue by mohammadne** [fluttercommunity/flutter_downloader#167]
in my app when I start to download an audio I get this:
```
D/skia    (17160): --- SkAndroidCodec::NewFromStream returned null
W/System.err(17160): java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.gerama.flutter_downloader.provider
W/System.err(17160): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:606)
W/System.err(17160): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
W/System.err(17160): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
W/System.err(17160): 	at vn.hunghd.flutterdownloader.IntentUtils.buildIntent(IntentUtils.java:23)
W/System.err(17160): 	at vn.hunghd.flutterdownloader.IntentUtils.validatedFileIntent(IntentUtils.java:35)
W/System.err(17160): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:360)
W/System.err(17160): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:189)
W/System.err(17160): 	at androidx.work.Worker$1.run(Worker.java:85)
W/System.err(17160): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err(17160): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err(17160): 	at java.lang.Thread.run(Thread.java:764)
I/WM-WorkerWrapper(17160): Worker result FAILURE for Work [ id=57594553-10eb-4737-a3c9-02cecbb8455d, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]
D/skia    (17160): --- SkAndroidCodec::NewFromStream returned null
I/chatty  (17160): uid=10128(com.gerama) pool-1-thread-3 identical 4 lines
D/skia    (17160): --- SkAndroidCodec::NewFromStream returned null
D/skia    (17160): --- SkAndroidCodec::NewFromStream returned null
I/chatty  (17160): uid=10128(com.gerama) pool-1-thread-3 identical 1 line
D/skia    (17160): --- SkAndroidCodec::NewFromStream returned null
W/System.err(17160): java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.gerama.flutter_downloader.provider
W/System.err(17160): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:606)
W/System.err(17160): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
W/System.err(17160): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
W/System.err(17160): 	at vn.hunghd.flutterdownloader.IntentUtils.buildIntent(IntentUtils.java:23)
W/System.err(17160): 	at vn.hunghd.flutterdownloader.IntentUtils.validatedFileIntent(IntentUtils.java:35)
W/System.err(17160): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:360)
W/System.err(17160): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:189)
W/System.err(17160): 	at androidx.work.Worker$1.run(Worker.java:85)
W/System.err(17160): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err(17160): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err(17160): 	at java.lang.Thread.run(Thread.java:764)
I/WM-WorkerWrapper(17160): Worker result FAILURE for Work [ id=c5e9fe33-84ad-47d8-9494-d68811edfc19, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]
```
do you know what is the problem ?
what should I do ?

**Comment by hnvn** [comment]
You miss this snip codes in your manifest:
```xml
<provider
     android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
     android:authorities="${applicationId}.flutter_downloader.provider"
     android:exported="false"
     android:grantUriPermissions="true">
      <meta-data
          android:name="android.support.FILE_PROVIDER_PATHS"
          android:resource="@xml/provider_paths"/>
</provider>
```

**Comment by mohammadne** [comment]
oh yes , thanks for fast response.
also I want to change the saved file name pattern .
how Can I achive it.

**Comment by mohammadne** [comment]
for example I want to save my mp3 file on storage without .mp3  name.
my purpose is to access this file only throw my application .

**Comment by hnvn** [comment]
If you want to prevent other applications from accessing your files, you should save them into the internal storage. See detail [here](https://developer.android.com/guide/topics/data/data-storage#filesInternal)
