### ISSUE TITLE
how to loads downloaded tasks ?

### ISSUE THREAD

**Issue by mohammadne** [fluttercommunity/flutter_downloader#183]
```
E/SQLiteLog( 2071): (1) no tables specified
E/MethodChannel#vn.hunghd/downloader( 2071): Failed to handle method call
E/MethodChannel#vn.hunghd/downloader( 2071): android.database.sqlite.SQLiteException: no tables specified (code 1): , while compiling: SELECT *
E/MethodChannel#vn.hunghd/downloader( 2071): at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
E/MethodChannel#vn.hunghd/downloader( 2071): at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
E/MethodChannel#vn.hunghd/downloader( 2071): at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
E/MethodChannel#vn.hunghd/downloader( 2071): at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
E/MethodChannel#vn.hunghd/downloader( 2071): at android.database.sqlite.SQLiteProgram.(SQLiteProgram.java:58)
E/MethodChannel#vn.hunghd/downloader( 2071): at android.database.sqlite.SQLiteQuery.(SQLiteQuery.java:37)
E/MethodChannel#vn.hunghd/downloader( 2071): at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
```
I am using:
final tasks = await FlutterDownloader.loadTasksWithRawQuery(query: 'SELECT *');

also it's worth to add a second page to your example to loads all the downloaded files because in most apps when we don't have internet and in offline mode we want to load all the downloaded files.

Thanks.

**Comment by hnvn** [comment]
```sql
SELECT * FROM task WHERE status=3
```
[document](https://github.com/fluttercommunity/flutter_downloader#load-tasks-with-conditions)
