### ISSUE TITLE
Shutting down VM

### ISSUE THREAD

**Issue by zhuxiwen** [fluttercommunity/flutter_downloader#190]
D/AndroidRuntime(12073): Shutting down VM                       
Syncing files to device Android SDK built for x86...                                                         E/AndroidRuntime(12073): FATAL EXCEPTION: main                  
Syncing files to device Android SDK built for x86...                                                         E/AndroidRuntime(12073): Process: com.example.yzy_flutter_android, PID: 12073
Syncing files to device Android SDK built for x86...                                                         E/AndroidRuntime(12073): java.lang.AssertionError: The Application must be implemented PluginRegistrantCallback
Syncing files to device Android SDK built for x86...                                                         E/AndroidRuntime(12073):        at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:106)
Syncing files to device Android SDK built for x86...                                                         E/AndroidRuntime(12073):        at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java:59)
Syncing files to device Android SDK built for x86...                                                         E/AndroidRuntime(12073):        at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:97)
Syncing files to device Android SDK built for x86...                                                         E/AndroidRuntime(12073):        at android.os.Handler.handleCallback(Handler.java:739)
Syncing files to device Android SDK built for x86...                                                         E/AndroidRuntime(12073):        at android.os.Handler.dispatchMessage(Handler.java:95)
Syncing files to device Android SDK built for x86...                                                         E/AndroidRuntime(12073):        at android.os.Looper.loop(Looper.java:148)
Syncing files to device Android SDK built for x86...                                                         E/AndroidRuntime(12073):        at android.app.ActivityThread.main(ActivityThread.java:5417)
Syncing files to device Android SDK built for x86...                                                         E/AndroidRuntime(12073):        at java.lang.reflect.Method.invoke(Native Method)
Syncing files to device Android SDK built for x86...                                                         E/AndroidRuntime(12073):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
Syncing files to device Android SDK built for x86...                                                         E/AndroidRuntime(12073):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Syncing files to device Android SDK built for x86...

**Comment by zhuxiwen** [comment]
On Android, I finally solved this problem with version 1.1.9
