### ISSUE TITLE
Compatibility issues with other plug-ins such as orientation: ^1.1.0

### ISSUE THREAD

**Issue by Lidinghua** [fluttercommunity/flutter_downloader#207]
_requestDownload();

W/WM-WorkSpec( 7894): Backoff delay duration less than minimum value
I/flutter ( 7894): Download task is enqueued with id(aa5c31d0-f14f-4f5d-aa93-641607bcbe4b)
I/WM-WorkerWrapper( 7894): Worker result SUCCESS for Work [ id=aa5c31d0-f14f-4f5d-aa93-641607bcbe4b, tags={ vn.hunghd.flutterdownloader.DownloadWorker, flutter_download_task } ]
E/AndroidRuntime( 7894): FATAL EXCEPTION: main
E/AndroidRuntime( 7894): Process: com.xingcyun.wzgl, PID: 7894
E/AndroidRuntime( 7894): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
E/AndroidRuntime( 7894): 	at android.view.OrientationEventListener.<init>(OrientationEventListener.java:69)
E/AndroidRuntime( 7894): 	at android.view.OrientationEventListener.<init>(OrientationEventListener.java:56)
E/AndroidRuntime( 7894): 	at com.github.sososdk.orientation.OrientationPlugin$1.<init>(OrientationPlugin.java:33)
E/AndroidRuntime( 7894): 	at com.github.sososdk.orientation.OrientationPlugin.<init>(OrientationPlugin.java:33)
E/AndroidRuntime( 7894): 	at com.github.sososdk.orientation.OrientationPlugin.registerWith(OrientationPlugin.java:44)
E/AndroidRuntime( 7894): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:36)
E/AndroidRuntime( 7894): 	at com.example.xy_material_flutter.MyApplication.registerWith(MyApplication.java:11)
E/AndroidRuntime( 7894): 	at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:124)
E/AndroidRuntime( 7894): 	at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java:59)
E/AndroidRuntime( 7894): 	at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:97)
E/AndroidRuntime( 7894): 	at android.os.Handler.handleCallback(Handler.java:761)
E/AndroidRuntime( 7894): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/AndroidRuntime( 7894): 	at android.os.Looper.loop(Looper.java:156)
E/AndroidRuntime( 7894): 	at android.app.ActivityThread.main(ActivityThread.java:6617)
E/AndroidRuntime( 7894): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7894): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
E/AndroidRuntime( 7894): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
I/Process ( 7894): Sending signal. PID: 7894 SIG: 9
Lost connection to device.

**Comment by bartekpacia** [comment]
No reproduction steps, no problem description. Closing.
