### ISSUE TITLE
loadTasks() throws FlutterDownloader.initialize() must be called first error (Android)

### ISSUE THREAD

**Issue by NickoftheSouth** [fluttercommunity/flutter_downloader#266]
I'm working on getting an app upadted to new plugin and Flutter

After calling `FlutterDownloader.initialize();`
and 'FlutterDownloader.registerCallback(downloadCallback)'
and `FlutterDownloader.enqueue()`
The callback method is triggered as the download updates and calls the method `await FlutterDownloader.loadTasks();`

this produces the error;
`E/flutter (27364): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter_downloader/src/downloader.dart': Failed assertion: line 111 pos 12: '_initialized': FlutterDownloader.initialize() must be called first
E/flutter (27364): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
E/flutter (27364): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
E/flutter (27364): #2      FlutterDownloader.loadTasks (package:flutter_downloader/src/downloader.dart:111:12)
E/flutter (27364): #3      DownloadManager.downloadCallback (package:nzamd/download/download_manager.dart:43:56)
E/flutter (27364): #4      callbackDispatcher.<anonymous closure> (package:flutter_downloader/src/callback_dispatcher.dart:24:13)
E/flutter (27364): #5      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:409:55)
E/flutter (27364): #6      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:377:54)
E/flutter (27364): #7      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
E/flutter (27364): #8      _invoke3.<anonymous closure> (dart:ui/hooks.dart:304:15)
E/flutter (27364): #9      _rootRun (dart:async/zone.dart:1126:13)
E/flutter (27364): #10     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (27364): #11     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (27364): #12     _invoke3 (dart:ui/hooks.dart:303:10)
E/flutter (27364): #13     _dispatchPlatformMessage (dart:ui/hooks.dart:163:5)`

This is the plugin version; 1.4.1
Flutter version; v1.15.4-pre.113

**Comment by iLeafSolutionsPvtLtd** [comment]
I did face the issue, put all operations in an async function and add await keyword before Flutter.initialize

**Comment by abhijitrajmane** [comment]
confirm first , call FlutterDownloader.initialize(); in your main.dart file
