### ISSUE TITLE
SocketTimeoutException on Android

### ISSUE THREAD

**Issue by valerybodak** [fluttercommunity/flutter_downloader#295]
I got java.net.SocketTimeoutException during downloading the file an. on Android:

```
java.net.SocketTimeoutException: timeout
2020-05-15 10:24:23.852 10660-10973/com.myapp W/System.err:     at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
2020-05-15 10:24:23.853 10660-10973/com.myapp  W/System.err:     at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
2020-05-15 10:24:23.853 10660-10973/com.myapp W/System.err:     at 
```

I see that the reason is in your **DownloadWorker.java** class. Timeout is 15 seconds. How to increase it?

_httpConn.setConnectTimeout(15000);
httpConn.setReadTimeout(15000);_

https://github.com/fluttercommunity/flutter_downloader/blob/master/android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java

Thank you.

**Comment by shunnokw** [comment]
Having the same problem
Overriding with HttpOverrides is not work

**Comment by valerybodak** [comment]
@shunnokw 
I forked flutter_downloader and increased timeout to 45 seconds. You can use it as temporary solution:
https://github.com/valerybodak/flutter_downloader

**Comment by niranjan-b-prajapati** [comment]
I am also facing the same problem. API takes time to respond as it has a lot of data to process and send the response as the blob. There should be some property to set from flutter end for this plugin where timeout can be set. As large data takes time to process and it is a generic scenario that might happen anytime. Request to please provide some property to manage timeout easily.

**Comment by firdavs97-cloud** [comment]
> /flutter (25273): 0 I/flutter (25273): DownloadTaskStatus(2) D/DownloadWorker(25273): Update notification: {notificationId: 84, title: http://192.168.1.21:3000/test.ipynb, status: 4, progress: -1} I/flutter (25273): -1 I/flutter (25273): DownloadTaskStatus(4) W/System.err(25273): java.net.SocketTimeoutException: timeout W/System.err(25273): at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:225) W/System.err(25273): at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263) W/System.err(25273): at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217) W/System.err(25273): at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:317) W/System.err(25273): at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:311) W/System.err(25273): at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:207) W/System.err(25273): at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:395) W/System.err(25273): at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:146) W/System.err(25273): at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:900) W/System.err(25273): at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:772) W/System.err(25273): at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475) W/System.err(25273): at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411) W/System.err(25273): at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542) W/System.err(25273): at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:294) W/System.err(25273): at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:208) W/System.err(25273): at androidx.work.Worker$1.run(Worker.java:85) W/System.err(25273): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) W/System.err(25273): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) W/System.err(25273): at java.lang.Thread.run(Thread.java:923) W/System.err(25273): Caused by: java.net.SocketException: Socket closed W/System.err(25273): at java.net.SocketInputStream.read(SocketInputStream.java:209) W/System.err(25273): at java.net.SocketInputStream.read(SocketInputStream.java:144) W/System.err(25273): at com.android.okhttp.okio.Okio$2.read(Okio.java:145) W/System.err(25273): at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213) W/System.err(25273): ... 16 more

same for me (

**Comment by alain8915** [comment]
same problem in 2022, any solution??

W/System.err(26991): java.net.SocketTimeoutException: timeout
W/System.err(26991):    at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:214)
W/System.err(26991):    at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
W/System.err(26991):    at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
W/System.err(26991):    at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
W/System.err(26991):    at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:395)
W/System.err(26991):    at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:372)
W/System.err(26991):    at java.io.InputStream.read(InputStream.java:101)
W/System.err(26991):    at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:344)
W/System.err(26991):    at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:201)
eam.java:144)
W/System.err(26991):    at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
W/System.err(26991):    ... 10 more

**Comment by alain8915** [comment]
i used de forked version of @valerybodak in my proyect, and have the same result.
I modified the pubspec.yaml to implement the forked version like this:



flutter_downloader:
    git: https://github.com/valerybodak/flutter_downloader.git
    
is correct??

**Comment by valerybodak** [comment]
@alain8915 In my fork the timeout is set to 45 seconds, but looks like 45 seconds is not enough for you.

**Comment by cristiancondorisegovia-bit** [comment]
java.net.SocketTimeoutException: timeout
	at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:214)
	at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFileMonitored(DownloadUtils.java:80)
	at net.kdt.pojavlaunch.mirrors.DownloadMirror.downloadFileMirrored(DownloadMirror.java:49)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.lambda$downloadFile$0$net-kdt-pojavlaunch-tasks-MinecraftDownloader$DownloaderTask(MinecraftDownloader.java:500)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask$$ExternalSyntheticLambda0.call(D8$$SyntheticClass:2)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFile(DownloadUtils.java:136)
	at net.kdt.pojavlaunch.utils.DownloadUtils.ensureSha1(DownloadUtils.java:161)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.downloadFile(MinecraftDownloader.java:499)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.verifyFileSha1(MinecraftDownloader.java:493)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.runCatching(MinecraftDownloader.java:478)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.run(MinecraftDownloader.java:466)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1100)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:1572)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:188)
	at java.net.SocketInputStream.read(SocketInputStream.java:143)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:1015)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:979)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:894)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:867)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
	... 25 more

**Comment by cristiancondorisegovia-bit** [comment]
java.net.SocketTimeoutException: timeout
	at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:214)
	at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFileMonitored(DownloadUtils.java:80)
	at net.kdt.pojavlaunch.mirrors.DownloadMirror.downloadFileMirrored(DownloadMirror.java:49)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.lambda$downloadFile$0$net-kdt-pojavlaunch-tasks-MinecraftDownloader$DownloaderTask(MinecraftDownloader.java:500)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask$$ExternalSyntheticLambda0.call(D8$$SyntheticClass:2)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFile(DownloadUtils.java:136)
	at net.kdt.pojavlaunch.utils.DownloadUtils.ensureSha1(DownloadUtils.java:161)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.downloadFile(MinecraftDownloader.java:499)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.verifyFileSha1(MinecraftDownloader.java:493)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.runCatching(MinecraftDownloader.java:478)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.run(MinecraftDownloader.java:466)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1100)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:1572)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:188)
	at java.net.SocketInputStream.read(SocketInputStream.java:143)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:1015)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:979)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:894)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:867)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
	... 25 more

**Comment by poliyongsoou-lgtm** [comment]
java.net.SocketTimeoutException: timeout
	at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:214)
	at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFileMonitored(DownloadUtils.java:80)
	at net.kdt.pojavlaunch.mirrors.DownloadMirror.downloadFileMirrored(DownloadMirror.java:49)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.lambda$downloadFile$0$net-kdt-pojavlaunch-tasks-MinecraftDownloader$DownloaderTask(MinecraftDownloader.java:500)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask$$ExternalSyntheticLambda0.call(D8$$SyntheticClass:2)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFile(DownloadUtils.java:136)
	at net.kdt.pojavlaunch.utils.DownloadUtils.ensureSha1(DownloadUtils.java:161)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.downloadFile(MinecraftDownloader.java:499)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.verifyFileSha1(MinecraftDownloader.java:493)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.runCatching(MinecraftDownloader.java:478)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.run(MinecraftDownloader.java:466)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1100)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:1572)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
	at java.net.SocketInputStream.read(SocketInputStream.java:173)
	at java.net.SocketInputStream.read(SocketInputStream.java:143)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:1015)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:979)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:894)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:867)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
	... 25 more
