### ISSUE TITLE
after a few minutes the internet connection drops by itself

### ISSUE THREAD

**Issue by Goolpe** [fluttercommunity/flutter_downloader#327]
I try to download multiple files (all files enqueued), if I lock screen, after 5+ minutes the internet connection drops by itself
Maybe there are some ways to keep the connection?
```
I/flutter ( 7439): INTERNET STATE ConnectivityResult.wifi
[log] [b447a05b-6f19-4d62-a781-852b3e6dd897, DownloadTaskStatus(2), 45]
I/flutter ( 7439): INTERNET STATE ConnectivityResult.wifi
[log] [04b074d4-887a-46f6-b71c-27bb827996b6, DownloadTaskStatus(2), 89]
I/flutter ( 7439): INTERNET STATE ConnectivityResult.wifi
W/System.err( 7439): javax.net.ssl.SSLException: Read error: ssl=0xdeda7ef8: I/O error during system call, Software caused connection abort
W/System.err( 7439): 	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
W/System.err( 7439): 	at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:411)
W/System.err( 7439): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:549)
W/System.err( 7439): 	at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
W/System.err( 7439): 	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
W/System.err( 7439): 	at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
W/System.err( 7439): 	at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:395)
W/System.err( 7439): 	at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:372)
W/System.err( 7439): 	at java.io.InputStream.read(InputStream.java:101)
W/System.err( 7439): 	at vn.hunghd.flutterdownloader.DownloadWorker.a(:335)
W/System.err( 7439): 	at vn.hunghd.flutterdownloader.DownloadWorker.m(:192)
W/System.err( 7439): 	at androidx.work.Worker$a.run(:85)
W/System.err( 7439): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 7439): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 7439): 	at java.lang.Thread.run(Thread.java:919)
I/flutter ( 7439): INTERNET STATE ConnectivityResult.none
[9f30bbf3-aebf-4e68-85ca-71248eb341a0, DownloadTaskStatus(4), -1]
I/flutter ( 7439): INTERNET STATE ConnectivityResult.none
[04b074d4-887a-46f6-b71c-27bb827996b6, DownloadTaskStatus(4), -1]
```

flutter doctor -v
```
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.388], locale ru-RU)
    • Flutter version 1.20.1 at C:\src\flutter
    • Framework revision 2ae34518b8 (6 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3) 
    • Android SDK at C:\Users\goool\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\goool\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

**Comment by lockiechen** [comment]
resolved? @Goolpe
