### ISSUE TITLE
First Open App Crash

### ISSUE THREAD

**Issue by bilaloz** [fluttercommunity/flutter_downloader#331]
Hello ,

I want to this package. But after installing app crash. Works fine in an empty project. I could not find any solution.

I read  (See upgrading pre 1.12 Android projects)

2020-08-18 14:29:34.000 25087-25087/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tamindir.app, PID: 25087
    java.lang.NoSuchMethodError: No static method createAsync(Landroid/os/Looper;)Landroid/os/Handler; in class Landroidx/core/os/HandlerCompat; or its super classes (declaration of 'androidx.core.os.HandlerCompat' appears in /data/app/com.tamindir.app-RwUl56-kD5wSWQRIjHaJKA==/base.apk)
        at androidx.work.impl.DefaultRunnableScheduler.<init>(DefaultRunnableScheduler.java:40)
        at androidx.work.Configuration.<init>(Configuration.java:106)
        at androidx.work.Configuration$Builder.build(Configuration.java:434)
        at vn.hunghd.flutterdownloader.FlutterDownloaderInitializer.onCreate(FlutterDownloaderInitializer.java:31)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1919)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6414)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5961)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5867)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1651)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2020-08-18 14:29:36.638 780-780/? E/lowmemorykiller: Error writing /proc/25087/oom_score_adj; errno=22
2020-08-18 14:29:36.670 1902-2882/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.android.launcher3/com.android.a1launcher.AndroidOneLauncher/28

**Comment by q876625596** [comment]
I had the same problem
flutter version：1.20.2

**Comment by Gaoxichao** [comment]
I had the same problem

**Comment by mrbulut** [comment]
i upgraded androidx.core version to 1.3.1, solved problem for me 

`
if (details.requested.group == 'androidx.core' && !details.requested.name.contains('androidx')) 
{
                    details.useVersion "1.3.1"
 }
`
