### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by Bonfra04** [fluttercommunity/flutter_downloader#339]
this is my code:

`
void downloadFile(String url, String filename) async {

    final status = await Permission.storage.request();

    if (status.isGranted) {
        final Directory externalDir = await getExternalStorageDirectory();

        final String id = await FlutterDownloader.enqueue(
            url: url,
            savedDir: externalDir.path,
            fileName: filename,
            showNotification: true,
            openFileFromNotification: true,
        );

        downloading.add(id);
    }
}
`

and when it runs, after the download has finished, throws this error:

W/System.err( 7182): java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority bonfra.stronzflix_mobile.flutter_downloader.provider
W/System.err( 7182): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:606)
W/System.err( 7182): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
W/System.err( 7182): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
W/System.err( 7182): 	at vn.hunghd.flutterdownloader.IntentUtils.buildIntent(IntentUtils.java:23)
W/System.err( 7182): 	at vn.hunghd.flutterdownloader.IntentUtils.validatedFileIntent(IntentUtils.java:35)
W/System.err( 7182): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:364)
W/System.err( 7182): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:192)
W/System.err( 7182): 	at androidx.work.Worker$1.run(Worker.java:85)
W/System.err( 7182): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 7182): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 7182): 	at java.lang.Thread.run(Thread.java:919)
I/WM-WorkerWrapper( 7182): Worker result FAILURE for Work [ id=402c2c07-e58f-435f-9df0-d39f49de4e23, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]

How can i solve it?

**Comment by codemewell** [comment]
This worked for me: https://github.com/fluttercommunity/flutter_downloader/issues/167#issuecomment-552059741
