### ISSUE TITLE
Error while downloading

### ISSUE THREAD

**Issue by lubritto** [fluttercommunity/flutter_downloader#377]
Hello

I'm using your plugin to download videos from my private Vimeo and for some reason, I'm getting this error. Can you help me to understand what is happening and why the download stopped work? It's really weird, all my videos are getting this error right now.

```dart
D/DownloadWorker(11914): Open connection to https://vod-progressive.akamaized.net/exp=1606159728~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F3646%2F18%2F468234303%2F2080567506.mp4~hmac=c6e0ebfd9696d97252fb52038f1e8cb38ed98886fd2a7144d421c10b31b809cf/vimeo-prod-skyfire-std-us/01/3646/18/468234303/2080567506.mp4?filename=Introducao+ao+Espanhol-HD+1080p.mp4
D/DownloadWorker(11914): Headers = {"Content-type": "video/mp4"}
D/DownloadWorker(11914): Content-Type = video/mp4
D/DownloadWorker(11914): Content-Length = 38768161
D/DownloadWorker(11914): Charset = null
D/DownloadWorker(11914): fileName = Espanhol0no0Enem.mp4
W/System.err(11914): java.net.ProtocolException: unexpected end of stream
W/System.err(11914): 	at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:421)
W/System.err(11914): 	at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
W/System.err(11914): 	at java.io.InputStream.read(InputStream.java:101)
W/System.err(11914): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:336)
W/System.err(11914): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:193)
W/System.err(11914): 	at androidx.work.Worker$1.run(Worker.java:85)
W/System.err(11914): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err(11914): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err(11914): 	at java.lang.Thread.run(Thread.java:761)
```

**Comment by Simouche** [comment]
how did you solve this?
