### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel vn.hunghd/downloader)

### ISSUE THREAD

**Issue by Bharavi26** [fluttercommunity/flutter_downloader#393]
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel vn.hunghd/downloader)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157)
    <asynchronous suspension>
    #1      FlutterDownloader.initialize (package:flutter_downloader/src/downloader.dart:36)
    <asynchronous suspension>
    

in debug apk its working fine...
but when i generate release apk and open that in mobile, white screen appear and this error generating in background

**Comment by surveshoeb** [comment]
Any update on this issue?

**Comment by surveshoeb** [comment]
> [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel vn.hunghd/downloader)
> #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157)
> 
> #1 FlutterDownloader.initialize (package:flutter_downloader/src/downloader.dart:36)
> 
> in debug apk its working fine...
> but when i generate release apk and open that in mobile, white screen appear and this error generating in background
> 
> i added **await FlutterDownloader.initialize();** in main.dart before runApp()
> but in release apk i am getting error

Hi @Bharavi26,

You need to update your prograudFile

**Comment by RomanSoviak** [comment]
If I don't have proguard

**Comment by DevTello** [comment]
editing proguard didn't help. Do we have other options?
