### ISSUE TITLE
Android: WorkManager cannot accupy more than 10240 bytes when serialized

### ISSUE THREAD

**Issue by danielkono** [fluttercommunity/flutter_downloader#432]
Hi,

cannot download files bigger than 1mb size on Android.
Getting this error:

```
E/MethodChannel#vn.hunghd/downloader( 8374): Failed to handle method call
E/MethodChannel#vn.hunghd/downloader( 8374): java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
E/MethodChannel#vn.hunghd/downloader( 8374): 	at androidx.work.Data.toByteArrayInternal(Data.java:417)
E/MethodChannel#vn.hunghd/downloader( 8374): 	at androidx.work.Data$Builder.build(Data.java:846)
E/MethodChannel#vn.hunghd/downloader( 8374): 	at vn.hunghd.flutterdownloader.FlutterDownloaderPlugin.buildRequest(FlutterDownloaderPlugin.java:138)
E/MethodChannel#vn.hunghd/downloader( 8374): 	at vn.hunghd.flutterdownloader.FlutterDownloaderPlugin.enqueue(FlutterDownloaderPlugin.java:177)
E/MethodChannel#vn.hunghd/downloader( 8374): 	at vn.hunghd.flutterdownloader.FlutterDownloaderPlugin.onMethodCall(FlutterDownloaderPlugin.java:82)
E/MethodChannel#vn.hunghd/downloader( 8374): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#vn.hunghd/downloader( 8374): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#vn.hunghd/downloader( 8374): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#vn.hunghd/downloader( 8374): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#vn.hunghd/downloader( 8374): 	at android.os.MessageQueue.next(MessageQueue.java:143)
E/MethodChannel#vn.hunghd/downloader( 8374): 	at android.os.Looper.loop(Looper.java:130)
E/MethodChannel#vn.hunghd/downloader( 8374): 	at android.app.ActivityThread.main(ActivityThread.java:5951)
E/MethodChannel#vn.hunghd/downloader( 8374): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#vn.hunghd/downloader( 8374): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/MethodChannel#vn.hunghd/downloader( 8374): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
E/MethodChannel#vn.hunghd/downloader( 8374): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
I/flutter ( 8374): Download task is failed with reason(Data cannot occupy more than 10240 bytes when serialized)

```

Using Flutter 1.22.6
with flutter_downloader 1.5.2
on Android 10 and Android 5.0

Did i miss something or is this a bug?

**Comment by EA-YOUHOU** [comment]
Up, how fix that ?

**Comment by danielkono** [comment]
Switched to `Dio` to download big files. Provides a progress callback but all the fancy management/info/notification stuff need to be implemented by yourself.

**Comment by EA-YOUHOU** [comment]
Do you have any example ?
