### ISSUE TITLE
Not able run release build

### ISSUE THREAD

**Issue by maxbhoria** [fluttercommunity/flutter_downloader#446]
Hi,

I am not able to run release build in Android using flutter run --release command because i am getting below error please help me that.

[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel vn.hunghd/downloader)
E/flutter ( 9310): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
E/flutter ( 9310): <asynchronous suspension>
E/flutter ( 9310): #1      FlutterDownloader.initialize (package:flutter_downloader/src/downloader.dart:36)
E/flutter ( 9310): <asynchronous suspension>
E/flutter ( 9310): #2      main (package:surge/main.dart:27)
E/flutter ( 9310): <asynchronous suspension>

Flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Xcode - develop for iOS and macOS
    ! Xcode 11.6.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.8.4 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.55.1)
[✓] Connected device (2 available)

**Comment by jabirmayar** [comment]
Hey, did you managed to solve the problem? I am having the exact same problem.

**Comment by gperez-88** [comment]
add this in `proguard-rules.pro`

```
## Android
-keep class androidx.lifecycle.** { *; }
-keep class com.google.android.** { *; }

## Other
-keepattributes *Annotation*
-keepattributes SourceFile,LineNumberTable
-keep public class * extends java.lang.Exception 
-keep class * implements io.flutter.plugin.common.MethodCallHandler { *; }
-keep class * implements io.flutter.plugin.common.PluginRegistry$PluginRegistrantCallback { *; }
-keepclasseswithmembers class * {
    native <methods>;
}
-keepclassmembers class * {
    static <fields>;
    static <methods>;
}

## flutter_downloader plugin
-keep class vn.hunghd.flutterdownloader.** { *; }
-keepclassmembers class vn.hunghd.flutterdownloader.** { *; }
```
