### ISSUE TITLE
Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by rohankandwal** [fluttercommunity/flutter_downloader#449]
Initialized FlutterDownloader

```
  await FlutterDownloader.initialize(
      debug: true // optional: set false to disable printing logs to console
  );
  runApp(MyApp());

```

For downloading in another **Route**
```
FlutterDownloader.registerCallback((String id, DownloadTaskStatus status, int progress) {
      if(status == DownloadTaskStatus.complete) {
        _extractZip();
      } else if(status == DownloadTaskStatus.failed) {

      }
    });
    final docDirectory = await getApplicationDocumentsDirectory();
    final taskId = await FlutterDownloader.enqueue(
      url: Constants.ENGLISH_MODULE_LIST[widget.index],
      savedDir: docDirectory.path,
      showNotification: true,
      // show download progress in status bar (for Android)
      openFileFromNotification:
          false, // click on notification to open downloaded file (for Android)
    );
```

Error
```
E/flutter (29387): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
E/flutter (29387): #0      FlutterDownloader.registerCallback (package:flutter_downloader/src/downloader.dart:389:71)
E/flutter (29387): #1      _ModuleWidgetState._downloadZip (package:example/core/widgets/module_widget/module_widget.dart:216:23)
E/flutter (29387): #2      _ModuleWidgetState.build.<anonymous closure> (package:example/core/widgets/module_widget/module_widget.dart:62:15)
E/flutter (29387): #3      _BlocConsumerState.build.<anonymous closure> (package:flutter_bloc/src/bloc_consumer.dart:130:26)
E/flutter (29387): #4      _BlocListenerBaseState._subscribe.<anonymous closure> (package:flutter_bloc/src/bloc_listener.dart:179:30)
E/flutter (29387): #5      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (29387): #6      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (29387): #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (29387): #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (29387): #9      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (29387): #10     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter (29387): #11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter (29387): #12     _rootRun (dart:async/zone.dart:1346:47)
E/flutter (29387): #13     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (29387): #14     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (29387): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (29387): #16     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (29387): #17     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (29387): #18     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (29387): #19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (29387): #20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (29387): #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**Comment by tzt1994** [comment]
I encountered the same problem, is there any effective suggestion

**Comment by igorkrz** [comment]
As you can see from this method your callback method must be top-level or static function.
```
static registerCallback(DownloadCallback callback) {
    assert(_initialized, 'FlutterDownloader.initialize() must be called first');
    final callbackHandle = PluginUtilities.getCallbackHandle(callback)!;
    assert(callbackHandle != null,
        'callback must be a top-level or a static function');
    _channel.invokeMethod(
        'registerCallback', <dynamic>[callbackHandle.toRawHandle()]);
  }
```

**Comment by bartekpacia** [comment]
@igorkrz is right.

Closing.
