### ISSUE TITLE
How can I download the file into AppPath?

### ISSUE THREAD

**Issue by ZhongMingKun** [fluttercommunity/flutter_downloader#48]
flutter_downloader: ^1.1.6
My files can't be opened by other application.So I use `getApplicationDocumentsDirectory()` .

**example/main.dart**
```dart
...
_localPath = (await _findLocalPath()) + '/Download';
Future<String> _findLocalPath() async {
  final directory =  await getApplicationDocumentsDirectory();
  return directory.path;
}
...
```
It's in debug mode.
But it happens error.
DownloadWorker showed `saveDir` is `/data/user/0/com.example.helloworld/app_flutter/Download`,
but error message is `Failed to find configured root that contains /data/data/com.example.helloworld/app_flutter/Download/Sand_Dunes_in_Death_Valley_National_Park.jpg` 
```
W/WM-WorkSpec(28239): Backoff delay duration less than minimum value
I/flutter (28239): Download task is enqueued with id(0e4f54f1-e6cd-4bd7-b422-e2438b6457fb)
I/flutter (28239): Download task (0e4f54f1-e6cd-4bd7-b422-e2438b6457fb) is in status (DownloadTaskStatus(1)) and process (0)
D/DownloadWorker(28239): DownloadWorker{url=https://upload.wikimedia.org/wikipedia/commons/b/b2/Sand_Dunes_in_Death_Valley_National_Park.jpg,filename=null,savedDir=/data/user/0/com.example.helloworld/app_flutter/Download,header={"auth": "test_for_sql_encoding"},isResume=false
I/flutter (28239): Download task (0e4f54f1-e6cd-4bd7-b422-e2438b6457fb) is in status (DownloadTaskStatus(2)) and process (0)
D/DownloadWorker(28239): Headers = {"auth": "test_for_sql_encoding"}
D/DownloadWorker(28239): Content-Type = image/jpeg
D/DownloadWorker(28239): Content-Length = 1363085
D/DownloadWorker(28239): Content-Disposition = null
D/DownloadWorker(28239): fileName = Sand_Dunes_in_Death_Valley_National_Park.jpg
I/flutter (28239): Download task (0e4f54f1-e6cd-4bd7-b422-e2438b6457fb) is in status (DownloadTaskStatus(2)) and process (1)
I/flutter (28239): Download task (0e4f54f1-e6cd-4bd7-b422-e2438b6457fb) is in status (DownloadTaskStatus(2)) and process (12)
I/flutter (28239): Download task (0e4f54f1-e6cd-4bd7-b422-e2438b6457fb) is in status (DownloadTaskStatus(2)) and process (23)
I/flutter (28239): Download task (0e4f54f1-e6cd-4bd7-b422-e2438b6457fb) is in status (DownloadTaskStatus(2)) and process (34)
I/flutter (28239): Download task (0e4f54f1-e6cd-4bd7-b422-e2438b6457fb) is in status (DownloadTaskStatus(2)) and process (45)
I/flutter (28239): Download task (0e4f54f1-e6cd-4bd7-b422-e2438b6457fb) is in status (DownloadTaskStatus(2)) and process (56)
I/flutter (28239): Download task (0e4f54f1-e6cd-4bd7-b422-e2438b6457fb) is in status (DownloadTaskStatus(2)) and process (67)
I/flutter (28239): Download task (0e4f54f1-e6cd-4bd7-b422-e2438b6457fb) is in status (DownloadTaskStatus(2)) and process (78)
I/flutter (28239): Download task (0e4f54f1-e6cd-4bd7-b422-e2438b6457fb) is in status (DownloadTaskStatus(2)) and process (89)
I/flutter (28239): Download task (0e4f54f1-e6cd-4bd7-b422-e2438b6457fb) is in status (DownloadTaskStatus(2)) and process (100)
I/flutter (28239): Download task (0e4f54f1-e6cd-4bd7-b422-e2438b6457fb) is in status (DownloadTaskStatus(4)) and process (-1)
W/System.err(28239): java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/com.example.helloworld/app_flutter/Download/Sand_Dunes_in_Death_Valley_National_Park.jpg
W/System.err(28239): 	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:739)
W/System.err(28239): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
W/System.err(28239): 	at vn.hunghd.flutterdownloader.IntentUtils.getOpenFileIntent(IntentUtils.java:23)
W/System.err(28239): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:218)
W/System.err(28239): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:102)
W/System.err(28239): 	at androidx.work.Worker$1.run(Worker.java:84)
W/System.err(28239): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err(28239): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err(28239): 	at java.lang.Thread.run(Thread.java:764)
I/WM-WorkerWrapper(28239): Worker result FAILURE for Work [ id=0e4f54f1-e6cd-4bd7-b422-e2438b6457fb, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]
```

**Comment by hnvn** [comment]
In Android, if you save files to `ApplicationDocumentsDirectory`, you can't open these files, because that's private storage of your application, other applications can't read data there. So, you have to use `ExternalStorageDirectory` and in order to access this storage, you have to handle permission request in Android

**Comment by ZhongMingKun** [comment]
> In Android, if you save files to `ApplicationDocumentsDirectory`, you can't open these files, because that's private storage of your application, other applications can't read data there. So, you have to use `ExternalStorageDirectory` and in order to access this storage, you have to handle permission request in Android

If these files are only used by my application,can I use `ApplicationDocumentsDirectory`?

**Comment by hnvn** [comment]
Yep, but feature `FlutterDownloader.open()` won't work in this case

**Comment by ZhongMingKun** [comment]
> Yep, but feature `FlutterDownloader.open()` won't work in this case

When I set `ApplicationDocumentsDirectory` to `saveDir`. It throw error.

**Comment by hnvn** [comment]
That error comes from `FileProvider` when it tries to give other applications permission to read data from a file in your application private storage. It happens when you save your files into the private storage while setting `openFileFromNotification` as `true`. In your case, setting `openFileFromNotification` as `false` (default) should resolve the matter.

**Comment by Uvais-Mohammad** [comment]
It worked for me. Thank you @hnvn
