### ISSUE TITLE
Files cannot be downloaded on Android 10 system

### ISSUE THREAD

**Issue by Huangkaiping** [fluttercommunity/flutter_downloader#516]
I/flutter ( 2369): Background Isolate Callback: task (e1b91c17-8fe8-4c43-9375-9fc0e362c7c6) is in status (DownloadTaskStatus(2)) and process (0)
D/DownloadWorker( 2369): Open connection to http://...shanghai.aliyuncs.com/ota/test/EWcmgF_app-release.apk
D/DownloadWorker( 2369): Update too frequently!!!!, but it is the final update, we should sleep a second to ensure the update call can be processed
I/flutter ( 2369): Background Isolate Callback: task (e1b91c17-8fe8-4c43-9375-9fc0e362c7c6) is in status (DownloadTaskStatus(4)) and process (-1)
D/DownloadWorker( 2369): Update notification: {notificationId: 13, title: http://...shanghai.aliyuncs.com/ota/test/EWcmgF_app-release.apk, status: 4, progress: -1}
W/System.err( 2369): java.io.IOException: Cleartext HTTP traffic to yat-smart.oss-cn-shanghai.aliyuncs.com not permitted
W/System.err( 2369): 	at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:124)
W/System.err( 2369): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:462)
W/System.err( 2369): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
W/System.err( 2369): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
W/System.err( 2369): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:289)
W/System.err( 2369): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:203)
W/System.err( 2369): 	at androidx.work.Worker$1.run(Worker.java:85)
W/System.err( 2369): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 2369): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 2369): 	at java.lang.Thread.run(Thread.java:929)
I/WM-WorkerWrapper( 2369): Worker result SUCCESS for Work [ id=e1b91c17-8fe8-4c43-9375-9fc0e362c7c6, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]
V/AudioManager( 2369): querySoundEffectsEnabled...

**Comment by Ezaldeen99** [comment]
DID YOU ADD  android:usesCleartextTraffic="true" TO YOUR AndroidManifest.xml ??

**Comment by kmno** [comment]
> DID YOU ADD android:usesCleartextTraffic="true" TO YOUR AndroidManifest.xml ??

I already added this line, but still not working

**Comment by BrilliantFish** [comment]
> 

same to me

**Comment by BrilliantFish** [comment]
>  I already added this line, but still not working
same to me

**Comment by BrilliantFish** [comment]
> I already added this line, but still not working

same to me
