### ISSUE TITLE
Downloading Failed with error of could not find the meta data for provider with authority.

### ISSUE THREAD

**Issue by abhiBirwa** [fluttercommunity/flutter_downloader#527]
i am getting this error when perform download operation.

java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.example.sskssvi.flutter_downloader.provider
W/System.err(23230): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:662)
W/System.err(23230): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:635)
W/System.err(23230): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:441)
W/System.err(23230): 	at vn.hunghd.flutterdownloader.IntentUtils.buildIntent(IntentUtils.java:23)
W/System.err(23230): 	at vn.hunghd.flutterdownloader.IntentUtils.validatedFileIntent(IntentUtils.java:35)
W/System.err(23230): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:416)
W/System.err(23230): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:208)
W/System.err(23230): 	at androidx.work.Worker$1.run(Worker.java:85)
W/System.err(23230): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(23230): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(23230): 	at java.lang.Thread.run(Thread.java:923)
I/WM-WorkerWrapper(23230): Worker result FAILURE for Work [ id=0be07fa4-b4f4-45cb-ad51-5bb224b63b0a, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]

flutter doctor:
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[!] Android Studio
    ✗ android-studio-dir = home/mindstack/android-studio
    ✗ Android Studio not found at home/mindstack/android-studio
[✓] VS Code (version 1.55.2)
[✓] Connected device (3 available)

flutter version:
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (2 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

Manifest file:

        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

        <provider
            android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true"
            android:requestLegacyExternalStorage="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>

**Comment by abhiBirwa** [comment]
please help me to resolve the problem.

**Comment by Andrius0124** [comment]
https://github.com/fluttercommunity/flutter_downloader/issues/167#issuecomment-552059741

worked for me
