### ISSUE TITLE
java.lang.NullPointerException: uri

### ISSUE THREAD

**Issue by claptv** [fluttercommunity/flutter_downloader#535]
Getting a null pointer exception from  ContentResolver.openAssetFileDescriptor method.  I can reproduce this problem with certain files most of times.

at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:133)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1484)
at android.content.ContentResolver.openOutputStream(ContentResolver.java:1234)
at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:358)
at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:208)

addFileToDownloadsApi29 method seems to return a valid uri; however, openOutputStream(uriApi29, "w") method at DownloadWorker.java:358 is causing this problem.

**outputStream = context.getContentResolver().openOutputStream(uriApi29, "w");**

I can access to the image with the HTTP Url with no problem.

Here is the log:

D/ConnectivityManager(14329): requestNetwork; CallingUid : 10918, CallingPid : 14329
D/DownloadWorker(14329): DownloadWorker{url=https://firebasestorage.googleapis.com:443/v0/b/clap4u-1b51b.appspot.com/o/files%2FhraoILBmVSRGixmOZb3juqVrcmh2%2F295a122d-72ed-4e90-8cf9-44486a03186d.png?alt=media&token=c56491e9-4437-4365-9b20-4e32efd48493,filename=Pursue Spray .png,savedDir=/storage/emulated/0/Download,header=,isResume=false
D/DownloadWorker(14329): Update notification: {notificationId: 33, title: Pursue Spray .png, status: 2, progress: 0}
D/DownloadWorker(14329): Open connection to https://firebasestorage.googleapis.com:443/v0/b/clap4u-1b51b.appspot.com/o/files%2FhraoILBmVSRGixmOZb3juqVrcmh2%2F295a122d-72ed-4e90-8cf9-44486a03186d.png?alt=media&token=c56491e9-4437-4365-9b20-4e32efd48493
I/System.out(14329): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(14329): (HTTPLog)-Static: isSBSettingEnabled false
D/DownloadWorker(14329): Content-Type = image/png
D/DownloadWorker(14329): Content-Length = 906615
D/DownloadWorker(14329): Charset = null
D/DownloadWorker(14329): fileName = Pursue Spray .png
D/DownloadWorker(14329): Update notification: {notificationId: 33, title: Pursue Spray .png, status: 4, progress: -1}
W/System.err(14329): **java.lang.NullPointerException: uri**
W/System.err(14329): 	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:133)
W/System.err(14329): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1484)
W/System.err(14329): 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1234)
W/System.err(14329): 	**at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:358)**
W/System.err(14329): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:208)
W/System.err(14329): 	at androidx.work.Worker$1.run(Worker.java:85)
W/System.err(14329): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(14329): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(14329): 	at java.lang.Thread.run(Thread.java:919)
I/WM-WorkerWrapper(14329): Worker result FAILURE for Work [ id=543e7685-40e8-4b7d-9848-cd27f6399210, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]
D/ConnectivityManager(14329): unregisterNetworkCallback; CallingUid : 10918, CallingPid : 14329

**Comment by AadneEM** [comment]
I'm having this same issue, but the file doesn't already exist. Other than that it's identical except for the file type being PDF.

It worked fine before, even if the file existed. Then it saved the file as `{filename}.pdf (n)` where n is a integer increasing by one for each file.

Device: OnePlus 7 Por
OS: Android 10

PS:
For the file name mentioned above, shouldn't the `(n)` part be before the file extension? When it's after it makes the OS not recognize which file type is it.

**Comment by bugrevealingbme** [comment]
Same as

**Comment by hnvn** [comment]
Duplicate of #548
