### ISSUE TITLE
Plugin crash on Android.

### ISSUE THREAD

**Issue by sergey-triputsco** [fluttercommunity/flutter_downloader#582]
I use flutter_downloader version 1.7.1. For some small number of users I observe the next crash:

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference
       at io.flutter.embedding.engine.dart.DartExecutor$DartCallback.toString(DartExecutor.java:22)
       at java.lang.String.valueOf(String.java:2896)
       at java.lang.StringBuilder.append(StringBuilder.java:132)
       at io.flutter.embedding.engine.dart.DartExecutor.executeDartCallback(DartExecutor.java:22)
       at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:58)
       at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java)
       at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:4)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

Crash happens in a second after launching the app.

**Comment by Taym95** [comment]
`FlutterCallbackInformation.lookupCallbackInformation` [can return null ](https://github.com/flutter/flutter/issues/73937), I think we should wrap `lookupCallbackInformation` ty/catch:

```
FlutterCallbackInformation flutterCallback;
try {
        flutterCallback = FlutterCallbackInformation.lookupCallbackInformation(callbackHandle);
    } catch (Exception e) {
        System.out.println(e.getMessage()); 
    }
 ```
 
 If you like this workaround, I can open PR and add this!

**Comment by DhruvamSharma** [comment]
I am having multiple crashes in the number of 300+ with every update.

**Comment by Taym95** [comment]
PR above should fix it

**Comment by DhruvamSharma** [comment]
Do you know when this would be merged? @Taym95 ?

**Comment by hnvn** [comment]
@Taym95 , could you provide more codes to handle the case that `flutterCallback` is null, because of without `flutterCallback` it can cause other issues.

**Comment by DhruvamSharma** [comment]
Hey, thank you for this product. But we need this urgently. Do you think we can come up with a solution? @hnvn @Taym95

**Comment by DhruvamSharma** [comment]
![Screenshot 2022-01-22 at 9 27 33 PM](https://user-images.githubusercontent.com/18664195/150646030-bb673d0d-e27c-4afe-8b57-a60fc75753e5.png)

There are too many crashes. We will have to shift away from flutter downloader.

**Comment by Taym95** [comment]
> @Taym95 , could you provide more codes to handle the case that `flutterCallback` is null, because of without `flutterCallback` it can cause other issues.

if flutterCallback is null, I am quitting the function, this is the solution I see all other flutter plugin using it, I don't see how to  handle that case

**Comment by Taym95** [comment]
> ![Screenshot 2022-01-22 at 9 27 33 PM](https://user-images.githubusercontent.com/18664195/150646030-bb673d0d-e27c-4afe-8b57-a60fc75753e5.png)
> 
> 
> 
> There are too many crashes. We will have to shift away from flutter downloader.

PR is merging, better to be patient, PR needs test and reviewing to be merged because of repository size, just for your information lot of people are doing this open source in their free time!

**Comment by DhruvamSharma** [comment]
Hi,
Ofcourse, I understand how people are working in their free time. I apologise if my tone turned out to be rude. Sincerely apologise.

**Comment by DhruvamSharma** [comment]
Thank you @Taym95 @hnvn for your time! 😄

**Comment by juzejunior** [comment]
Good work guys, thank you!
