### ISSUE TITLE
file not downloading due to following 

### ISSUE THREAD

**Issue by niazsigmads** [fluttercommunity/flutter_downloader#596]
issue:
Update too frequently!!!!, this should be dropped

detals log:
W/WM-WorkSpec(12325): Backoff delay duration less than minimum value
I/flutter (12325):  value after enqueue is 3dcfe547-8645-4e1f-96e1-8be023c7c811
D/DownloadWorker(12325): DownloadWorker{url=https://ncip.scdwapps.com/uploads/files/Downloads/NCAP-Bond-Factsheet.pdf,filename=null,savedDir=/storage/emulated/0/Android/data/com.spiralclick.ncap.ncap/files,header=,isResume=false,status=1
D/DownloadWorker(12325): Update notification: {notificationId: 17, title: https://ncip.scdwapps.com/uploads/files/Downloads/NCAP-Bond-Factsheet.pdf, status: 2, progress: 0}
D/DownloadWorker(12325): Open connection to https://ncip.scdwapps.com/uploads/files/Downloads/NCAP-Bond-Factsheet.pdf
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(2), 0]
D/DownloadWorker(12325): Content-Type = application/pdf
D/DownloadWorker(12325): Content-Length = 409424
D/DownloadWorker(12325): Charset = null
D/DownloadWorker(12325): Content-Disposition = null
D/DownloadWorker(12325): fileName = NCAP-Bond-Factsheet.pdf
D/DownloadWorker(12325): Update too frequently!!!!, this should be dropped
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(2), 1]
D/DownloadWorker(12325): Update too frequently!!!!, this should be dropped
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(2), 7]
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(2), 13]
D/DownloadWorker(12325): Update too frequently!!!!, this should be dropped
D/DownloadWorker(12325): Update too frequently!!!!, this should be dropped
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(2), 19]
D/DownloadWorker(12325): Update too frequently!!!!, this should be dropped
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(2), 25]
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(2), 31]
D/DownloadWorker(12325): Update too frequently!!!!, this should be dropped
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(2), 37]
D/DownloadWorker(12325): Update too frequently!!!!, this should be dropped
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(2), 43]
D/DownloadWorker(12325): Update too frequently!!!!, this should be dropped
D/DownloadWorker(12325): Update too frequently!!!!, this should be dropped
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(2), 49]
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(2), 55]
D/DownloadWorker(12325): Update too frequently!!!!, this should be dropped
D/DownloadWorker(12325): Update too frequently!!!!, this should be dropped
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(2), 61]
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(2), 67]
D/DownloadWorker(12325): Update too frequently!!!!, this should be dropped
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(2), 73]
D/DownloadWorker(12325): Update too frequently!!!!, this should be dropped
D/DownloadWorker(12325): Update too frequently!!!!, this should be dropped
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(2), 79]
D/DownloadWorker(12325): Update too frequently!!!!, this should be dropped
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(2), 85]
D/DownloadWorker(12325): Update too frequently!!!!, this should be dropped
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(2), 91]
D/DownloadWorker(12325): Update too frequently!!!!, this should be dropped
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(2), 97]
D/DownloadWorker(12325): Update too frequently!!!!, this should be dropped
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(2), 100]
D/DownloadWorker(12325): Update too frequently!!!!, but it is the final update, we should sleep a second to ensure the update call can be processed
I/flutter (12325): UI Isolate Callback: [3dcfe547-8645-4e1f-96e1-8be023c7c811, DownloadTaskStatus(4), -1]
D/DownloadWorker(12325): Update notification: {notificationId: 17, title: https://ncip.scdwapps.com/uploads/files/Downloads/NCAP-Bond-Factsheet.pdf, status: 4, progress: -1}
W/System.err(12325): java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.spiralclick.ncap.ncap.flutter_downloader.provider
W/System.err(12325): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:662)
W/System.err(12325): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:635)
W/System.err(12325): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:441)
W/System.err(12325): 	at vn.hunghd.flutterdownloader.IntentUtils.buildIntent(IntentUtils.java:23)
W/System.err(12325): 	at vn.hunghd.flutterdownloader.IntentUtils.validatedFileIntent(IntentUtils.java:35)
W/System.err(12325): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:437)
W/System.err(12325): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:232)
W/System.err(12325): 	at androidx.work.Worker$1.run(Worker.java:86)
W/System.err(12325): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(12325): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(12325): 	at java.lang.Thread.run(Thread.java:919)
I/WM-WorkerWrapper(12325): Worker result FAILURE for Work [ id=3dcfe547-8645-4e1f-96e1-8be023c7c811, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]

**Comment by Bidhanrai** [comment]
Same problem.
For ios it's fine.But for Android.. it successfully downloads the file.. But at last it throws failed status in the sequence below
DownloadTaskStatus(2)==>running
DownloadTaskStatus(2)==>running
DownloadTaskStatus(2)==>running
DownloadTaskStatus(2)==>running
DownloadTaskStatus(3)==>Complete  (but if we check file is downloaded)
DownloadTaskStatus(4)==>Failed (at last it throws this status)
