### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'int vn.hunghd.flutterdownloader.DownloadTask.status' on a null object reference

### ISSUE THREAD

**Issue by m-ochyra** [fluttercommunity/flutter_downloader#616]
Exception on flutter_downloader version 1.7.2

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int vn.hunghd.flutterdownloader.DownloadTask.status' on a null object reference
       at vn.hunghd.flutterdownloader.DownloadWorker.onStopped(DownloadWorker.java:178)
       at androidx.work.ListenableWorker.stop(ListenableWorker.java:283)
       at androidx.work.impl.workers.ConstraintTrackingWorker.onStopped(ConstraintTrackingWorker.java:181)
       at androidx.work.ListenableWorker.stop(ListenableWorker.java:283)
       at androidx.work.impl.WorkerWrapper.interrupt(WorkerWrapper.java:397)
       at androidx.work.impl.Processor.interrupt(Processor.java:340)
       at androidx.work.impl.Processor.stopWork(Processor.java:190)
       at androidx.work.impl.utils.StopWorkRunnable.run(StopWorkRunnable.java:73)
       at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

**Comment by juzejunior** [comment]
Same here

**Comment by vishnunew** [comment]
I am also getting same error when downloading started and trying to remove when running downloads or completed download.

**Comment by bartekpacia** [comment]
@m-ochyra Can you tell me more about the problem? When did it happen? Some example code so I can try to reproduce it would help as well.

**Comment by felipecastrosales** [comment]
updates about this?
