### ISSUE TITLE
having issue while uploading apk to playstore(due to Android 12 )

### ISSUE THREAD

**Issue by shabeerseeroo1** [fluttercommunity/flutter_downloader#676]
facing an issue while uploading the app to the play store, this issue will get on while giving exported as false as per the documentation, and the new rule of android the exported should be true in order to work in android 12 and greater devices and  if set exported as true in provider the application will be crashed
![image](https://user-images.githubusercontent.com/68379664/174795541-df8c626a-b563-417e-9013-bcd8b4394c4b.png)

**Comment by rekire** [comment]
You should provide the stacktrace instead of a non helpful screenshot of your manifest

**Comment by RobbyOkta19** [comment]
i have same issue :
if android:exported="true" app will crash 

Launching lib/main.dart on SM A505F in debug mode...
Running Gradle task 'assembleDebug'...
Warning: The plugin permission_handler_android requires Android SDK version 33.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to /Users/kominfotanahdatar/MobileProject/portal/android/app/build.gradle:
android {
  compileSdkVersion 33
  ...
}

../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selectable.dart:459:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^
../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/overlay_manager.dart:138:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      if (SchedulerBinding.instance!.schedulerPhase ==
                           ^
../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/overlay_manager.dart:140:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!
                         ^
../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/web_selection_manager.dart:119:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!
                       ^
../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/overlay.dart:141:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    if (SchedulerBinding.instance!.schedulerPhase ==
                         ^
../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/overlay.dart:143:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback(_markNeedsBuild);
                       ^
../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/overlay.dart:193:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    if (SchedulerBinding.instance!.schedulerPhase ==
                         ^
../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/overlay.dart:195:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback(_markNeedsBuild);
                       ^
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
E/AndroidRuntime(28735): FATAL EXCEPTION: main
E/AndroidRuntime(28735): Process: portal.tanahdatar.egov, PID: 28735
E/AndroidRuntime(28735): java.lang.RuntimeException: Unable to get provider vn.hunghd.flutterdownloader.DownloadedFileProvider: java.lang.SecurityException: Provider must not be exported
E/AndroidRuntime(28735): 	at android.app.ActivityThread.installProvider(ActivityThread.java:8215)
E/AndroidRuntime(28735): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7746)
E/AndroidRuntime(28735): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7566)
E/AndroidRuntime(28735): 	at android.app.ActivityThread.access$1500(ActivityThread.java:301)
E/AndroidRuntime(28735): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
E/AndroidRuntime(28735): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(28735): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(28735): 	at android.app.ActivityThread.main(ActivityThread.java:8653)
E/AndroidRuntime(28735): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28735): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(28735): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/AndroidRuntime(28735): Caused by: java.lang.SecurityException: Provider must not be exported
E/AndroidRuntime(28735): 	at androidx.core.content.FileProvider.attachInfo(FileProvider.java:410)
E/AndroidRuntime(28735): 	at android.app.ActivityThread.installProvider(ActivityThread.java:8210)
E/AndroidRuntime(28735): 	... 10 more

**Comment by Kishan-Somaiya** [comment]
I'm getting the same issue, unable to run or publish the app when exported is set to true, did you guys find the solution ?

**Comment by Kishan-Somaiya** [comment]
@rekire @bartekpacia guys can you help us with this?

**Comment by rekire** [comment]
It is now quiet clear for me why this build fails. However I'm not sure where this comes from.

@RobbyOkta19 can you provide a screenshot of your merged manifest? I think that a transitive dependency is causing that. In the merged manifest should be a `DownloadedFileProvider` can you detect from the color from which dependency this line comes from?

**Comment by rekire** [comment]
Did you add it as mentioned in the [readme file](https://github.com/fluttercommunity/flutter_downloader#open-downloaded-file-from-notification)? it must be `android:exported="false"`

**Comment by Kishan-Somaiya** [comment]
if you add android:exported="false" play store won't accept your build with android 12 or higher.

**Comment by rekire** [comment]
I'm not using that file provider in production so I never faced this issue. However I cannot find any references that they must be exported. [That `android:exported="true"` requirement](https://developer.android.com/about/versions/12/behavior-changes-12#exported) just applies for activities, services, or broadcast receivers that use intent filters. Instead I found a [reference](https://support.google.com/faqs/answer/7496913) which recommend to set it to **false** for providers.

Could you guys please show the error message of the PlayStore itself? I would expect that there is a link to a documentation, that would help me to understand the issue.

To be honest this provider is my mind that is some kind of legacy code, but I had no time for a bigger refactoring which I which I would like make that provider not necessary. However that will take based on my limited times realistic a couple of month.
