### ISSUE TITLE
 httpConn.contentType must not be null error when download file with ext db after upgrade lib from 1.8.4 to 1.9.0 - 1.9.1

### ISSUE THREAD

**Issue by eggysudianto** [fluttercommunity/flutter_downloader#753]
error download file with extension `.db` from my server, but if download `.db `from other cloud server it's fine. 
other example I put pdf file in my server, and it's can downloaded. So error is specify extension `.db`

error after upgrade lib from 1.8.4 to 1.9.0 - 1.9.1

```
W/System.err(32262): java.lang.NullPointerException: httpConn.contentType must not be null
W/System.err(32262): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.kt:342)
W/System.err(32262): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.kt:208)
W/System.err(32262): 	at androidx.work.Worker$1.run(Worker.java:86)
W/System.err(32262): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(32262): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(32262): 	at java.lang.Thread.run(Thread.java:764)
I/WM-WorkerWrapper(32262): Worker result FAILURE for Work [ id=dab2a537-23d2-4a94-82bf-2f6670c1a89e, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]
D/ConnectivityManager(32262): unregisterNetworkCallback; CallingUid : 10247, CallingPid : 32262
```

this my code

```
WidgetsFlutterBinding.ensureInitialized();
await FlutterDownloader.initialize(debug: true, ignoreSsl: true);
FlutterDownloader.registerCallback(downloadCallback);
requestDownload('${urlPrefixImages}sqlite/sqlite.db', 'sqlite.db', localPath);
```

```
static Future<void> requestDownload(
      String _url, String _name, String localPath) async {
    final savedDir = Directory(localPath);
    await savedDir.create(recursive: true).then((value) async {
      String? _taskid = await FlutterDownloader.enqueue(
        url: _url,
        fileName: _name,
        savedDir: localPath,
        showNotification: false,
        openFileFromNotification: false,
      );
    });
  }
```

flutter doctor
```
[√] Flutter (Channel stable, 3.3.7, on Microsoft Windows [Version 10.0.22000.1165], locale en-ID)
    • Flutter version 3.3.7 on channel stable at D:\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (7 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at D:\SDK\android_sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 33.0.0
    • ANDROID_HOME = D:\SDK\android_sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Enterprise 2017 15.9.49)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
    • Visual Studio Enterprise 2017 version 15.9.28307.2019
    X Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Connected device (4 available)
    • SM T385 (mobile)  • da59fab9 • android-arm    • Android 9 (API 28)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.22000.1165]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 107.0.5304.88
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 106.0.1370.47

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by umairtechmaven** [comment]
I am facing the same issue how you have solved this?

**Comment by umairtechmaven** [comment]
```
W/System.err(10971): java.lang.NullPointerException: httpConn.contentType must not be null
W/System.err(10971): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.kt:342)
W/System.err(10971): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.kt:208)
W/System.err(10971): 	at androidx.work.Worker$1.run(Worker.java:86)
W/System.err(10971): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(10971): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(10971): 	at java.lang.Thread.run(Thread.java:923)
```

Facing same issue

**Comment by kevin-138** [comment]
@umairtechmaven got the same issu you found anything yet?

**Comment by umairtechmaven** [comment]
@kevin-138 Still not.

**Comment by umairtechmaven** [comment]
@eggysudianto 
are you able to solve this?

**Comment by eggysudianto** [comment]
> @eggysudianto Have you get any solution for this?

I don't have any solution, just use 1.8.4 version, never upgrade
