### ISSUE TITLE
During the download process, disconnect the network and restore the network, causing the application crash.

### ISSUE THREAD

**Issue by LinChengChun** [fluttercommunity/flutter_downloader#77]
D/Surface ( 3963): Surface::setBuffersDimensions(this=0x7f8861fc00,w=1080,h=1920)
I/flutter ( 3963): ConnectivityResult.wifi
D/AndroidRuntime( 3963): Shutting down VM
D/SQLiteDatabase( 3963): beginTransaction()
D/SQLiteDatabase( 3963): endTransaction()
D/SQLiteDatabase( 3963): beginTransaction()
D/SQLiteDatabase( 3963): endTransaction()
D/SQLiteDatabase( 3963): beginTransaction()
D/SQLiteDatabase( 3963): beginTransaction()
D/SQLiteDatabase( 3963): endTransaction()
D/SQLiteDatabase( 3963): beginTransaction()
D/SQLiteDatabase( 3963): endTransaction()
D/SQLiteDatabase( 3963): endTransaction()
D/SQLiteDatabase( 3963): beginTransaction()
D/SQLiteDatabase( 3963): endTransaction()
E/AndroidRuntime( 3963): FATAL EXCEPTION: main
E/AndroidRuntime( 3963): Process: com.nufront.euhtbss, PID: 3963
E/AndroidRuntime( 3963): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in androidx.work.impl.constraints.trackers.NetworkStateTracker$NetworkStateBroadcastReceiver@1ed5879c
E/AndroidRuntime( 3963): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:965)
E/AndroidRuntime( 3963): 	at android.os.Handler.handleCallback(Handler.java:815)
E/AndroidRuntime( 3963): 	at android.os.Handler.dispatchMessage(Handler.java:104)
E/AndroidRuntime( 3963): 	at android.os.Looper.loop(Looper.java:194)
E/AndroidRuntime( 3963): 	at android.app.ActivityThread.main(ActivityThread.java:5889)
E/AndroidRuntime( 3963): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3963): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 3963): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
E/AndroidRuntime( 3963): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)
E/AndroidRuntime( 3963): Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@18a97487 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@911efb4[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
E/AndroidRuntime( 3963): 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
E/AndroidRuntime( 3963): 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
E/AndroidRuntime( 3963): 	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:298)
E/AndroidRuntime( 3963): 	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:503)
E/AndroidRuntime( 3963): 	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:644)
E/AndroidRuntime( 3963): 	at androidx.work.impl.background.systemalarm.WorkTimer.startTimer(WorkTimer.java:82)
E/AndroidRuntime( 3963): 	at androidx.work.impl.background.systemalarm.DelayMetCommandHandler.onAllConstraintsMet(DelayMetCommandHandler.java:100)
E/AndroidRuntime( 3963): 	at androidx.work.impl.constraints.WorkConstraintsTracker.onConstraintMet(WorkConstraintsTracker.java:150)
E/AndroidRuntime( 3963): 	at androidx.work.impl.constraints.controllers.ConstraintController.updateCallback(ConstraintController.java:134)
E/AndroidRuntime( 3963): 	at androidx.work.impl.constraints.controllers.ConstraintController.onConstraintChanged(ConstraintController.java:141)
E/AndroidRuntime( 3963): 	at androidx.work.impl.constraints.trackers.ConstraintTracker.setState(ConstraintTracker.java:103)
E/AndroidRuntime( 3963): 	at androidx.work.impl.constraints.trackers.NetworkStateTracker$NetworkStateBroadcastReceiver.onReceive(NetworkStateTracker.java:170)
E/AndroidRuntime( 3963): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:953)
E/AndroidRuntime( 3963): 	... 8 more

**Comment by Audhil** [comment]
Does anyone have a solution?

**Comment by SSebigo** [comment]
Have the same problem, the only message I have is this one:

```
I/flutter (16351): Download task is enqueued with id(5bf90b63-daf4-4dca-b1e8-7be82269ec8c)
Lost connection to device.
Exited (sigterm)
```
Is there any solution for this ?

**Comment by Nais0ne** [comment]
Facing the same issue as SSebigo, my app always crashes when I try to download something, with exactly the same messages

**Comment by salmaahhmed** [comment]
@LinChengChun if you're still having this problem can you please post an example of how you're using the framework to provide more information ?
