### ISSUE TITLE
My android target version is 22, with permissions declared in the manifest file, runs on android api27, and it appears in an error

### ISSUE THREAD

**Issue by Jonyker** [fluttercommunity/flutter_downloader#80]
```
D/DownloadWorker(27840): Content-Type = application/vnd.android.package-archive
Syncing files to device MI 8 SE...                                      
D/DownloadWorker(27840): Content-Length = 11558153              
D/DownloadWorker(27840): Content-Disposition = attachment; filename=qqlite_3.7.1.704_android_r110206_GuanWang_537057973_release_10000484.apk
D/DownloadWorker(27840): fileName = qqlite_3.7.1.704_android_r110206_GuanWang_537057973_release_10000484.apk       
W/System.err(27840): java.io.FileNotFoundException: /storage/emulated/0/qqlite_3.7.1.704_android_r110206_GuanWang_537057973_release_10000484.apk (No such file or directory)
W/System.err(27840):    at java.io.FileOutputStream.open0(Native Method)                                           
W/System.err(27840):    at java.io.FileOutputStream.open(FileOutputStream.java:287)                                
W/System.err(27840):    at java.io.FileOutputStream.<init>(FileOutputStream.java:223)                              
W/System.err(27840):    at java.io.FileOutputStream.<init>(FileOutputStream.java:142)                              
W/System.err(27840):    at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:192)        
W/System.err(27840):    at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:104)              
W/System.err(27840):    at androidx.work.Worker$1.run(Worker.java:85)                                              
W/System.err(27840):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)         
W/System.err(27840):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)         
W/System.err(27840):    at java.lang.Thread.run(Thread.java:764)                                                   
I/WM-WorkerWrapper(27840): Worker result SUCCESS for Work [ id=bcee6055-6d4e-4fb8-8419-256d4e737ad8, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]
```

**Comment by IlyaMax** [comment]
@Jonyker have you found the solution?
