### ISSUE TITLE
[Android] Example app crash after installing: Unable to instantiate activity ComponentInfo 

### ISSUE THREAD

**Issue by huynguyennovem** [fluttercommunity/flutter_downloader#805]
**Describe the bug**

The example app crashed right after installing.

**To Reproduce**

Run example code at https://github.com/fluttercommunity/flutter_downloader/tree/master/example on the latest Flutter beta and master channels.

Flutter beta: `3.7.0-1.5.pre`
Flutter master: `3.8.0-1.0.pre.32`

<details>
<summary>Crash logs</summary>

```bash
Launching lib/main.dart on RMX2001 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...
E/AndroidRuntime(27058): FATAL EXCEPTION: main
E/AndroidRuntime(27058): Process: vn.hunghd.example, PID: 27058
E/AndroidRuntime(27058): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{vn.hunghd.example/vn.hunghd.example.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "vn.hunghd.example.MainActivity" on path: DexPathList[[zip file "/data/app/~~KefrkMLzMsj1LbBkF7IyBw==/vn.hunghd.example-vkRl0DG_RfW9SJNzRfTWZQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~KefrkMLzMsj1LbBkF7IyBw==/vn.hunghd.example-vkRl0DG_RfW9SJNzRfTWZQ==/lib/arm64, /data/app/~~KefrkMLzMsj1LbBkF7IyBw==/vn.hunghd.example-vkRl0DG_RfW9SJNzRfTWZQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64, /vendor/lib64, /odm/lib64, /my_product/lib64, /my_carrier/lib64]]
E/AndroidRuntime(27058): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3643)
E/AndroidRuntime(27058): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3903)
E/AndroidRuntime(27058): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(27058): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(27058): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(27058): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2328)
E/AndroidRuntime(27058): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(27058): 	at android.os.Looper.loop(Looper.java:255)
E/AndroidRuntime(27058): 	at android.app.ActivityThread.main(ActivityThread.java:8212)
E/AndroidRuntime(27058): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27058): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
E/AndroidRuntime(27058): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
E/AndroidRuntime(27058): Caused by: java.lang.ClassNotFoundException: Didn't find class "vn.hunghd.example.MainActivity" on path: DexPathList[[zip file "/data/app/~~KefrkMLzMsj1LbBkF7IyBw==/vn.hunghd.example-vkRl0DG_RfW9SJNzRfTWZQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~KefrkMLzMsj1LbBkF7IyBw==/vn.hunghd.example-vkRl0DG_RfW9SJNzRfTWZQ==/lib/arm64, /data/app/~~KefrkMLzMsj1LbBkF7IyBw==/vn.hunghd.example-vkRl0DG_RfW9SJNzRfTWZQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64, /vendor/lib64, /odm/lib64, /my_product/lib64, /my_carrier/lib64]]
E/AndroidRuntime(27058): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime(27058): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(27058): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(27058): 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
E/AndroidRuntime(27058): 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
E/AndroidRuntime(27058): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
E/AndroidRuntime(27058): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3631)
E/AndroidRuntime(27058): 	... 11 more

```
</details>

**Expected behavior**

No crash.

**Device information:**

- Device: `Realme 6` 
- OS: `Android 11`
- plugin version: `flutter_downloader: ^1.10.1+2`

**Comment by huynguyennovem** [comment]
Filled PR: https://github.com/fluttercommunity/flutter_downloader/pull/806
