### ISSUE TITLE
FATAL EXCEPTION DownloadWorker.java:94

### ISSUE THREAD

**Issue by leonetosoft** [fluttercommunity/flutter_downloader#81]
Hi,

Exception is causing the application to close,
detail: the internet is slow
```
E/AndroidRuntime(30589): FATAL EXCEPTION: pool-1-thread-1
E/AndroidRuntime(30589): Process: com.upaki.medmidia, PID: 30589
E/AndroidRuntime(30589): java.lang.NullPointerException: Attempt to read from field 'int vn.hunghd.flutterdownloader.DownloadTask.primaryId' on a null object reference
E/AndroidRuntime(30589): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:94)
E/AndroidRuntime(30589): 	at androidx.work.Worker$1.run(Worker.java:84)
E/AndroidRuntime(30589): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/AndroidRuntime(30589): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/AndroidRuntime(30589): 	at java.lang.Thread.run(Thread.java:764)
I/Process (30589): Sending signal. PID: 30589 SIG: 9
Lost connection to device.
```

**Comment by johnny-stevie** [comment]
whats your android manifest.xml?

**Comment by gleesonger** [comment]
I get this same issue when removing a file that is currently running.

From looking at the code I suspect the following is happening: [cancelWorkById](https://github.com/fluttercommunity/flutter_downloader/blob/master/android/src/main/java/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.java#L311) is asynchronous and before it has completed the entry in the database is removed and doWork is called. In this case the [loadTask](https://github.com/fluttercommunity/flutter_downloader/blob/master/android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java#L180) in doWork returns null but this is never checked and causes the function to throw a null pointer exception further down.

The correct way to fix this is probably to await cancelWorkById before deleting the file and removing the entry from the table but I am not familiar enough with the codebase to know how much work that is to implement.

A quick hack is to put in a null check just after [loadTask](https://github.com/fluttercommunity/flutter_downloader/blob/master/android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java#L180) but, if what I suspect above is right, an attempt to [delete the file](https://github.com/fluttercommunity/flutter_downloader/blob/master/android/src/main/java/vn/hunghd/flutterdownloader/FlutterDownloaderPlugin.java#L322) could throw an error. 

The approach I have then to this issue is to cancel not remove the task and on each app launch I perform a clean up exercise removing any cancelled tasks and deleting file contents. I am a little nervous with this approach as I suspect there are some edge cases which will cause a crash but hopefully they are of very low chance.
