### ISSUE TITLE
java.lang.NullPointerException when using audio_service

### ISSUE THREAD

**Issue by qq125183592** [fluttercommunity/flutter_downloader#82]
When running AudioService.start by flutter plugin audio_service, the app crashes. 

The following exception about FlutterDownloaderPlugin is thrown :
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.app.Activity.getApplication()' on a null object reference
E/CrashReport(  811): 	at vn.hunghd.flutterdownloader.FlutterDownloaderPlugin.registerWith(FlutterDownloaderPlugin.java:67)
E/CrashReport(  811): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:33)
E/CrashReport(  811): 	at com.letabc.zaxt.MainApplication.registerWith(MainApplication.java:18)
E/CrashReport(  811): 	at com.ryanheise.audioservice.AudioServicePlugin$ClientHandler$4.onPlay(AudioServicePlugin.java:267)
E/CrashReport(  811): 	at com.ryanheise.audioservice.AudioService$MediaSessionCallback$1.run(AudioService.java:525)
E/CrashReport(  811): 	at com.ryanheise.audioservice.AudioService$MediaSessionCallback.play(AudioService.java:541)
E/CrashReport(  811): 	at com.ryanheise.audioservice.AudioService$MediaSessionCallback.onPlay(AudioService.java:523)
E/CrashReport(  811): 	at android.support.v4.media.session.MediaSessionCompat$Callback$StubApi21.onPlay(MediaSessionCompat.java:1405)
E/CrashReport(  811): 	at android.support.v4.media.session.MediaSessionCompatApi21$CallbackProxy.onPlay(MediaSessionCompatApi21.java:196)
E/CrashReport(  811): 	at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1219)
E/CrashReport(  811): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/CrashReport(  811): 	at android.os.Looper.loop(Looper.java:150)
E/CrashReport(  811): 	at android.app.ActivityThread.main(ActivityThread.java:5546)
E/CrashReport(  811): 	at java.lang.reflect.Method.invoke(Native Method)
E/CrashReport(  811): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
E/CrashReport(  811): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

```

**Comment by eslamira** [comment]
facing the same issue here
any updates

**Comment by Mahfoud047** [comment]
@hnvn Any updates for this issue, Please? 
Here is the Bug report discribed in audio_service package for another plugin (wifi plugin), it may help:

> Flutter's new background execution feature (described here: https://medium.com/flutter-io/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124) allows plugins to be registered in a background context (e.g. a Service). The problem is that the wifi plugin assumes that the context for plugin registration is an activity with this line of code:
> 
```
 WifiManager wifiManager = (WifiManager) 

 registrar.activity().getApplicationContext().getSystemService(Context.WIFI_SERVICE);
```

> 
> registrar.activity() may now return null, and this leads to a NullPointerException:

> The solution is to change the above line of code to this:
> 

```
WifiManager wifiManager = (WifiManager)registrar.activeContext().getApplicationContext().getSystemService(Context.WIFI_SERVICE);
```

>

**Comment by johnny-stevie** [comment]
I am still facing the same issue, the updates haven't helped prevent this.

**Comment by alexmercerind** [comment]
It is still causing the problem.

**Comment by sarbazx** [comment]
I am also having this problem @hnvn
