### ISSUE TITLE
Path Mismatch in getApplicationDocumentsDirectory Usage on Android 13

### ISSUE THREAD

**Issue by claptv** [fluttercommunity/flutter_downloader#920]
The getApplicationDocumentsDirectory method is returning a path formatted as `**/data/user/0**/com.example.app/app_flutter`, which is causing a failure in a plugin that expects a path in the format of `**/data/data/**com.example.app/app_flutter/Download/image.jpg`.

I created `Download` directory under `/data/user/0**/com.example.app/app_flutter`

D/DownloadWorker(10806): Update notification: {notificationId: 22, title: image.jpg, status: FAILED, progress: -1}
W/System.err(10806): java.lang.IllegalArgumentException: Failed to find configured root that contains **/data/data/com.example.app/app_flutter/Download/image.jpg**
W/System.err(10806): 	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:825)
W/System.err(10806): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:450)
W/System.err(10806): 	at vn.hunghd.flutterdownloader.IntentUtils.buildIntent(IntentUtils.kt:19)
W/System.err(10806): 	at vn.hunghd.flutterdownloader.IntentUtils.validatedFileIntent(IntentUtils.kt:36)
W/System.err(10806): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.kt:446)
W/System.err(10806): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.kt:206)
W/System.err(10806): 	at androidx.work.Worker$1.run(Worker.java:86)
W/System.err(10806): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W/System.err(10806): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W/System.err(10806): 	at java.lang.Thread.run(Thread.java:1012)

**To Reproduce**

**Expected behavior**

Downloads must be completed successfully, and files should be correctly saved in the **/data/user/0**/com.example.app/app_flutter directory without any errors.

**Screenshots**

**Desktop (please complete the following information):**

**Device information:**

- Device: Emulator (Pixel 7 Pro API 33)
- OS: Android 13
- plugin version 1.11.5

**Additional context**

**Comment by vzhilong** [comment]
I facing the same bug here.

**Comment by claptv** [comment]
Same problem with a temporary directory.

Update notification: {notificationId: 66, title: 20231129_040121_696.jpg, status: FAILED, progress: -1}
W/System.err(17793): java.lang.IllegalArgumentException: Failed to find configured root that contains `/data/data/com.example.app/**cache**/image.jpg`

**Comment by kjxbyz** [comment]
same issue.

```
java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/io.demo/app_flutter/e5efe08bc224411199839dca0f4c1da1.pdf
W/System.err(11171): 	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:825)
W/System.err(11171): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:450)
W/System.err(11171): 	at vn.hunghd.flutterdownloader.IntentUtils.buildIntent(IntentUtils.kt:19)
W/System.err(11171): 	at vn.hunghd.flutterdownloader.IntentUtils.validatedFileIntent(IntentUtils.kt:36)
W/System.err(11171): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.kt:446)
W/System.err(11171): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.kt:206)
W/System.err(11171): 	at androidx.work.Worker$1.run(Worker.java:86)
W/System.err(11171): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
W/System.err(11171): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
W/System.err(11171): 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by yogendra-algoworks** [comment]
Below soln resolve issue.

<img width="1432" alt="Screenshot 2024-05-20 at 3 23 47 PM" src="https://github.com/fluttercommunity/flutter_downloader/assets/111557708/9c2f635e-c24c-4b72-9e93-b54d98bb32e1">

**Comment by 93Pd9s8Jt** [comment]
> Below soln resolve issue.
> 
> You have to add xml/provider_paths.xml in android res folder
> <img alt="Screenshot 2024-05-20 at 3 23 47 PM" width="1432" src="https://private-user-images.githubusercontent.com/111557708/332022022-9c2f635e-c24c-4b72-9e93-b54d98bb32e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAyNDU3NjEsIm5iZiI6MTc0MDI0NTQ2MSwicGF0aCI6Ii8xMTE1NTc3MDgvMzMyMDIyMDIyLTljMmY2MzVlLWMyNGMtNGI3Mi05ZTkzLWI1NGQ5OGJiMzJlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIyMlQxNzMxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDc5ZjY1ODRiYWQ2MzU4YTM2ZWU0MjQ4ZTIzYTcyZmY1MGY5MDlkNzI0OTdiOGJmMjYzZjA2YzIxMjFiZjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.k4Dto-NzTjTOGTm85k0oJFyJIN_BrgTc24x54Ng5Xqc">

This didn't work for me, but the similar solution for #291 did.
