### ISSUE TITLE
Deleting file and download again the same file not working

### ISSUE THREAD

**Issue by Nandhini-GA** [fluttercommunity/flutter_downloader#934]
When deleting file from the file explorer and download the same file again always failing

In iOS it is working, Issue with android device only.

**Steps:**
1. download a file  (FlutterDownloader.enqueue())
2. delete the file manually from downloads
3. download the same file FlutterDownloader.enqueue())

**Console Erro:**
D/DownloadWorker(12373): Update notification: {notificationId: 8, title: GOA-1924573-2180476 (2).pdf, status: FAILED, progress: -1}

W/System.err(12373): java.lang.NullPointerException

W/System.err(12373): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.kt:385)

W/System.err(12373): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.kt:206)

W/System.err(12373): 	at androidx.work.Worker$1.run(Worker.java:86)

W/System.err(12373): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)

W/System.err(12373): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

W/System.err(12373): 	at java.lang.Thread.run(Thread.java:919)

I/WM-WorkerWrapper(12373): Worker result FAILURE for Work [ id=4ef9a1d3-ff16-467f-b797-5fb7d3a981b5, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]

**Comment by microorbit** [comment]
Try with changing the name of file. 
You can simply add timestamp at the end of the file name.
